name: Build ToaruOS

on:
  push:
    branches: [ "*" ]
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          chmod +x ./util/docker-build.sh
          ./util/docker-build.sh

      - name: Upload OS Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: toaruos-image
          path: |
            *.iso
            *.img
          if-no-files-found: warn
