name: Build ToaruOS

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Repo Files
        run: |
          echo "=== ЧТО ЛЕЖИТ В КОРНЕ: ==="
          ls -la
          echo "=== ЧТО ЛЕЖИТ В ПАПКЕ UTIL (если есть): ==="
          ls -la util || echo "Папки util нет"
